#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${REPO_ROOT}/apps/web/.env.local"

START_AFTER_BOOTSTRAP=0
if [[ "${1:-}" == "--start" ]]; then
  START_AFTER_BOOTSTRAP=1
fi

info() { printf "\033[36m[INFO]\033[0m %s\n" "$*"; }
warn() { printf "\033[33m[WARN]\033[0m %s\n" "$*"; }
ok()   { printf "\033[32m[OK]\033[0m %s\n" "$*"; }
err()  { printf "\033[31m[ERR]\033[0m %s\n" "$*"; }

has_cmd() { command -v "$1" >/dev/null 2>&1; }

require_cmd() {
  local cmd="$1"
  local tip="$2"
  if ! has_cmd "${cmd}"; then
    err "缺少命令: ${cmd}"
    printf "      建议: %s\n" "${tip}"
    exit 1
  fi
}

upsert_env() {
  local key="$1"
  local value="$2"
  local file="$3"
  local escaped
  escaped="$(printf '%s' "${value}" | sed -e 's/[\/&]/\\&/g')"
  if grep -qE "^${key}=" "${file}"; then
    sed -i '' -E "s/^${key}=.*/${key}=${escaped}/" "${file}"
  else
    printf "%s=%s\n" "${key}" "${value}" >> "${file}"
  fi
}

info "检查基础依赖..."
require_cmd "node" "安装 Node.js (建议 v22+)"
require_cmd "pnpm" "安装 pnpm (建议 v11+)"
require_cmd "python3" "安装 Python 3.9+"

if ! has_cmd "soffice"; then
  warn "未检测到 soffice（LibreOffice）。VLM 文档解析会受影响。"
fi
if ! has_cmd "codex"; then
  warn "未检测到 codex CLI。默认 VLM 后端是 codex，建议安装后再运行。"
fi

info "安装 JS 依赖..."
cd "${REPO_ROOT}"
pnpm install
ok "JS 依赖安装完成"

info "安装 Python 依赖..."
python3 -m pip install --user \
  pymupdf \
  python-pptx \
  sentence-transformers \
  fastembed \
  FlagEmbedding
ok "Python 依赖安装完成"

if [[ -f "${ENV_FILE}" ]]; then
  warn "检测到已有 ${ENV_FILE}，将仅补全/更新关键变量。"
else
  info "创建 ${ENV_FILE}"
  mkdir -p "$(dirname "${ENV_FILE}")"
  cat > "${ENV_FILE}" <<'EOF'
# Generated by scripts/bootstrap_new_machine.sh
EOF
fi

INDATA_KEY_INPUT="${INDATA_API_KEY:-}"
if [[ -z "${INDATA_KEY_INPUT}" ]]; then
  printf "请输入 INDATA_API_KEY（输入时不可见，回车确认）："
  IFS= read -r -s INDATA_KEY_INPUT
  printf "\n"
fi

if [[ -z "${INDATA_KEY_INPUT}" ]]; then
  warn "你没有输入 INDATA_API_KEY。脚本继续执行，但 GPT-5.5 路径不可用。"
fi

upsert_env "INDATA_API_KEY" "${INDATA_KEY_INPUT}" "${ENV_FILE}"
upsert_env "INDATA_BASE_URL" "${INDATA_BASE_URL:-https://model.indata.cc/v1}" "${ENV_FILE}"
upsert_env "SP_VLM_BACKEND" "${SP_VLM_BACKEND:-codex}" "${ENV_FILE}"
upsert_env "SP_CODEX_MODEL" "${SP_CODEX_MODEL:-gpt-5.5}" "${ENV_FILE}"
ok ".env.local 配置完成"

if [[ ${START_AFTER_BOOTSTRAP} -eq 1 ]]; then
  info "执行构建并启动服务..."
  pnpm --filter @gov-validator/web build
  pnpm --filter @gov-validator/web start
else
  printf "\n"
  ok "初始化完成。下一步可执行："
  printf "  cd %s\n" "${REPO_ROOT}"
  printf "  pnpm --filter @gov-validator/web build\n"
  printf "  pnpm --filter @gov-validator/web start\n"
  printf "  打开: http://127.0.0.1:5186/app\n"
fi

